### ISSUE TITLE
Suggestions for Bento

### ISSUE THREAD

**Issue by aniruddha76** [aniruddha76/github-readme-bento#4]
Try my github readme Bento and suggest some elements or changes you would like to see.

**Comment by SufyaanKhateeb** [comment]
<img src="https://github-readme-bento.vercel.app/stats/sufyaankhateeb?theme=dark" />

- Seems to be working fine.
- Recommend you to add more query params for more information similar to something provided by github-readme-stats.

Is it possible to embed other html tags instead of just using image tag?

**Comment by aniruddha76** [comment]
> ![](https://camo.githubusercontent.com/c6b326ace4a0983038f5674aee7a586679b94485b70e437d303a87df833a23f5/68747470733a2f2f6769746875622d726561646d652d62656e746f2e76657263656c2e6170702f73746174732f7375667961616e6b6861746565623f7468656d653d6461726b)
> 
> * Seems to be working fine.
> * Recommend you to add more query params for more information similar to something provided by github-readme-stats.
> 
> Is it possible to embed other html tags instead of just using image tag?

Thank you for trying it out!!

And yes you can embed this bento in other HTML tags such as. 

1. `object` tag

    ```html
    <object data="https://github-readme-bento.vercel.app/stats/SufyaanKhateeb" type="image/svg+xml"></object>
    ```

2. `iframe` tag

    ```html
    <iframe src="https://github-readme-bento.vercel.app/stats/SufyaanKhateeb" frameborder="0"></iframe>
    ```

3.  `embed` tag

    ```html
    <embed src="https://github-readme-bento.vercel.app/stats/SufyaanKhateeb" type="image/svg+xml">
    ```
  
if you liked my project consider leaving star and share with others!!
