### ISSUE TITLE
Issue with language names

### ISSUE THREAD

**Issue by aniruddha76** [aniruddha76/github-readme-bento#5]
Im facing a problem with language names, im using a function to return language and their colors

```
  function getLanguageColor(language) {
    const colors = {
      HTML: "#e34c26",
      CSS: "#563d7c",
      JavaScript: "#f1e05a",
      TypeScript: "#3178c6",
      C: "#555555",
      Java: "#b07219",
      Python: "#3572A5",
      Vue: "#41b883",
      Ruby: "#701516",
      Rust: "#dea584",
      Dockerfile: "#384d54",
      Shell: "#89e051",
      Hcl: "#844FBA",
      Jinja: "#a52a22",
      Mustache: "#724b3b",
      Processing: "#0095D8"
    };
    return colors[language] || "#ccc";
  }
}
```
the thing is i cant use `C++` and language names with space in between such as `Jupyter Notebook` how to solve this issue?

**Comment by ShadowFax1731** [comment]
Try setting the key-value pairs as strings. e.g.
const colors = {
"HTML": "#ccc"
}
Use this syntax and you can probably set "C++"; "Color of your choice"
Maybe this works

**Comment by ShadowFax1731** [comment]
Would also work for all types of key names such as "Jupyter Notebook' etc.

**Comment by aniruddha76** [comment]
okay i will check

**Comment by aniruddha76** [comment]
> Would also work for all types of key names such as "Jupyter Notebook' etc.

Hello again, Thank you for your suggestion using string format is working well, 
If you like this project, please consider giving it a star and sharing it with others!
